#define TK_EOL                             1
#define TK_IDENT                           2
#define TK_EQ                              3
#define TK_LPAREN                          4
#define TK_RPAREN                          5
#define TK_COMMA                           6
#define TK_OP                              7
#define TK_DOT                             8
#define TK_TYPE                            9
#define TK_HEX                            10
#define TK_FLOAT                          11
#define TK_INT                            12
#define TK_STR                            13
#define TK_CHR                            14
#define TK_REG                            15
#define TK_LABEL                          16
#define TK_LBRACK                         17
#define TK_RBRACK                         18
#define TK_PERCENT                        19
#define TK_FUNCTION                       20
#define TK_END                            21
#define TK_COLON                          22
